// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz5QttFUTsSar7QJ2IlXJpDLq0dPdEQdU',
    appId: '1:115348965997:web:2f7196bee01c9314220d64',
    messagingSenderId: '115348965997',
    projectId: 'fir-auth-ddefe',
    authDomain: 'fir-auth-ddefe.firebaseapp.com',
    storageBucket: 'fir-auth-ddefe.firebasestorage.app',
    measurementId: 'G-B5MEJZ6Q19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCwSUJh2BZNDSGfzaAft7XXfFjUe2Xbw',
    appId: '1:115348965997:android:0e2bc512b5e8896c220d64',
    messagingSenderId: '115348965997',
    projectId: 'fir-auth-ddefe',
    storageBucket: 'fir-auth-ddefe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf1gffFHVm59nMiohSCb54QsZ9mnJxTpw',
    appId: '1:115348965997:ios:006eb7a925058304220d64',
    messagingSenderId: '115348965997',
    projectId: 'fir-auth-ddefe',
    storageBucket: 'fir-auth-ddefe.firebasestorage.app',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf1gffFHVm59nMiohSCb54QsZ9mnJxTpw',
    appId: '1:115348965997:ios:006eb7a925058304220d64',
    messagingSenderId: '115348965997',
    projectId: 'fir-auth-ddefe',
    storageBucket: 'fir-auth-ddefe.firebasestorage.app',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz5QttFUTsSar7QJ2IlXJpDLq0dPdEQdU',
    appId: '1:115348965997:web:51a47b1254da7c06220d64',
    messagingSenderId: '115348965997',
    projectId: 'fir-auth-ddefe',
    authDomain: 'fir-auth-ddefe.firebaseapp.com',
    storageBucket: 'fir-auth-ddefe.firebasestorage.app',
    measurementId: 'G-B7NHXCJBBF',
  );
}
